"""extend document schema for ingestion

Revision ID: 6ef8f659348c
Revises: 96209cd7447c
Create Date: 2026-07-12 17:10:52.590945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef8f659348c'
down_revision: Union[str, Sequence[str], None] = '96209cd7447c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('content_type', sa.String(length=255), nullable=True))
    op.add_column('document', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('document', sa.Column('checksum', sa.String(length=64), nullable=False))
    op.add_column('document', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_document_checksum'), 'document', ['checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_checksum'), table_name='document')
    op.alter_column('document', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('document', 'error_message')
    op.drop_column('document', 'checksum')
    op.drop_column('document', 'file_type')
    op.drop_column('document', 'content_type')
    # ### end Alembic commands ###
