"""refactor chunk schema for ingestion

Revision ID: 96209cd7447c
Revises: 86cfd16d1c0f
Create Date: 2026-07-12 16:56:31.308161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96209cd7447c'
down_revision: Union[str, Sequence[str], None] = '86cfd16d1c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('chunk_id', sa.String(length=64), nullable=False))
    op.add_column('chunk', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('chunk', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('chunk', sa.Column('char_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chunk_chunk_id'), 'chunk', ['chunk_id'], unique=False)
    op.create_unique_constraint('uq_chunk_document_id_chunk_id', 'chunk', ['document_id', 'chunk_id'])
    op.create_check_constraint(
        'ck_chunk_char_count_non_negative',
        'chunk',
        'char_count >= 0',
    )
    op.create_check_constraint(
        'ck_chunk_page_range_valid',
        'chunk',
        'page_start IS NULL OR page_end IS NULL OR page_end >= page_start',
    )
    op.drop_column('chunk', 'page')
    op.drop_column('chunk', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_chunk_page_range_valid',
        'chunk',
        type_='check',
    )
    op.drop_constraint(
        'ck_chunk_char_count_non_negative',
        'chunk',
        type_='check',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunk', sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_chunk_document_id_chunk_id', 'chunk', type_='unique')
    op.drop_index(op.f('ix_chunk_chunk_id'), table_name='chunk')
    op.drop_column('chunk', 'char_count')
    op.drop_column('chunk', 'page_end')
    op.drop_column('chunk', 'page_start')
    op.drop_column('chunk', 'chunk_id')
    # ### end Alembic commands ###
